### ISSUE TITLE
Script applies also to floating windows

### ISSUE THREAD

**Issue by gianmarcogg03** [phenax/bsp-layout#39] opened 2021-12-30 23:28 UTC
I'm using bspwm on Arch Linux and when I have a desktop set to the tall layout and open more than one floating window, the previous one gets squished weirdly as if it was tiled and the script wanted to resize it. The script's functionality should be limited only to tiled windows.

**Comment by phenax** [comment] 2022-06-11 17:08
Duplicate of #26

**Closed by phenax** 2022-06-11 17:08 UTC
