### ISSUE TITLE
Ignore floating or hidden window

### ISSUE THREAD

**Issue by aztecrabbit** [phenax/bsp-layout#26] opened 2021-04-01 05:17 UTC
I have floating and hidden window, can you resize the parent of the floating or hidden window to match to the other one? like this

Tiled

```
_______________
|        |    |
|        |----|
|        | xx |
|        |----|
|________|____|

```

Floating or Hidden

```
_______________
|        |    |
|        |    |
|        |    |
|        |----|
|________|____|

```

What i want

```
_______________
|        |    |
|        |    |
|        |----|
|        |    |
|________|____|

```

**Comment by a2n-s** [comment] 2022-06-16 17:11
Hi @aztecrabbit :wave: 

i'll have a look at that shortly and try to reproduce the bug :ok_hand:

**Comment by a2n-s** [comment] 2022-06-18 10:19
@aztecrabbit

> I have floating and hidden window, can you resize
> the parent of the floating
> or hidden window to match to the other one?
>
i can reproduce that bug, even in the `tall` layout which is by definition supposed to do that.

@phenax, i think that floating and hidden windows should simply be ignored by the layouts of `bsp-layout` :thinking:

correct me if i'm wrong, but `bsp-layout` is really a TILLING-layout manager, right?

there's already 2 opened issues that mention the fact that floating, and here hidden, windows are used to compute the different sizes of the windows of the layout...
what about opening a PR to fix this bug once and for all? :yum:

**Comment by phenax** [comment] 2022-06-19 11:48
> i think that floating and hidden windows should simply be ignored by the layouts of bsp-layout

Yes. I remember trying to work on this a while ago but had a lot of buggy behavior for the filters. See if you can take this on.

**Comment by a2n-s** [comment] 2022-06-19 11:57
> > i think that floating and hidden windows should simply be ignored by the layouts of bsp-layout
> 
> Yes. I remember trying to work on this a while ago but had a lot of buggy behavior for the filters. See if you can take this on.
>
gotcha :wink:

**Comment by a2n-s** [comment] 2022-07-10 10:13
hi @aztecrabbit and @phenax :wave: 

the fun thing is that i'm not able to reproduce that with `0.0.10-1` :thinking: 

[here](https://imgur.com/a/xaoRUzT) is what i get with, i believe, the setup that lead to your issue @aztecrabbit, right? :confused: 

can any one of you two confirm this issue in `0.0.10-1`? :yum:

**Comment by aztecrabbit** [comment] 2022-07-18 04:26
Sorry, i can't test this project right now, i'm not using bspwm anymore. If version `0.0.10-1` is fixed for hidden mode too (i see only floating in your gif), this issue have been fixed then

**Comment by a2n-s** [comment] 2022-07-19 15:41
> If version `0.0.10-1` is fixed for hidden mode too (i see only floating in your gif), this issue have been fixed then
>
yup you're right, i kinda forgot about them :wink:

[here](https://imgur.com/a/rSPRr7T) is the same clip as above but with a hidden window :+1: 
and i think it does what you wanted back when you opened this issue, right? :thinking: 

i think i'll close this issue :confused: 
i would have liked to help, but that'll be a bit hard without being able to reproduce anything...

> Sorry, i can't test this project right now, i'm not using bspwm anymore.
>
no worries :yum: 
i you happen to move to `bspwm` again someday and find yourself in the same unexpected situation, feel free to reopen this issue and let us know what you find out :wink:

**Closed by a2n-s** 2022-07-19 15:41 UTC
Labels: bug, priority:high
